const router = require('koa-router')()
const loginController = require('./admin/login/loginController')
const loginPostController = require('./admin/login/loginPostController')
const indexController = require('./admin/index/indexController')
const logoutController = require('./admin/login/logoutController')
const navController = require('./admin/nav/navController')
const navAdd = require('./admin/nav/navAdd')
const navAddPost = require('./admin/nav/navAddPost')
const navDel = require('./admin/nav/navDel')
const navUpdate = require('./admin/nav/navUpdate')
const navUpdatePost = require('./admin/nav/navUpdatePost')
const articleAdd = require('./admin/article/articleAdd')
const articleAddPost = require('./admin/article/articleAddPost')
const uploadImg = require('./admin/article/uploadImg')
const articleCheck = require('./admin/article/articleCheck')
const readArticle = require('./admin/article/readArticle')
const delArticle = require('./admin/article/delArticle')
const changeArticleStatus = require('./admin/article/changeArticleStatus')
const userInfo = require('./admin/Info/userInfo')
const setUserInfo = require('./admin/Info/setUserInfo')
const uploadAvatar = require('./admin/Info/uploadAvatar')
const tools = require('./admin/tools/tools')
const toolAdd = require('./admin/tools/toolAdd')
const toolAddPost = require('./admin/tools/toolAddPost')
const toolDelete = require('./admin/tools/toolDelete')
const toolUpdate = require('./admin/tools/toolUpdate')
const toolUpdatePost = require('./admin/tools/toolUpdatePost')
// get
router.get('/admin',loginController)
router.get('/admin/index',indexController)
router.get('/admin/logout',logoutController)
router.get('/admin/nav',navController)
router.get('/admin/navAdd',navAdd)
router.get('/admin/navDel',navDel)
router.get('/admin/navUpdate',navUpdate)
router.get('/admin/articleAdd',articleAdd)
router.get('/admin/articleCheck',articleCheck)
router.get('/admin/readArticle',readArticle)
router.get('/admin/delArticle',delArticle)
router.get('/admin/articleCheck/changeStatus',changeArticleStatus)
router.get('/admin/userInfo',userInfo)
router.get('/admin/tools',tools)
router.get('/admin/toolAdd',toolAdd)
router.get('/admin/toolDelete',toolDelete)
router.get('/admin/toolUpdate',toolUpdate)


// post
router.post('/admin/navUpdatePost',navUpdatePost)
router.post('/admin/navAddPost',navAddPost)
router.post('/admin',loginPostController)
router.post('/admin/articleAddPost',articleAddPost)
router.post('/admin/file/uploadImg',uploadImg)
router.post('/admin/file/uploadAvatar',uploadAvatar)
router.post('/admin/setUserInfo',setUserInfo)
router.post('/admin/toolAdd',toolAddPost)
router.post('/admin/toolUpdate',toolUpdatePost)





module.exports = router